default: &default
  adapter: postgresql
  encoding: unicode
  username: matchmaker
  password: sandbox  

  host: localhost
  pool: 5

production:
  <<: *default
  database: rails_demo_development

test:
  <<: *default
  database: rails_demo_test