default: &default
  adapter: postgresql
  encoding: unicode
  username: tps
  password: tps
  host: localhost
  pool: 5

development:
  <<: *default
  database: rails_demo_development

test:
  <<: *default
  database: rails_demo_test
